### PR TITLE
Fix test failing with Zope 4.2.1

### PR DESCRIPTION
**Pull request by tschorr**
by explicity passing a referrer.

### CODE REVIEW

**Comment by tschorr** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Error in the `CMFQuickInstallerTool` [tests](https://jenkins.plone.org/job/pull-request-5.2-3.7/963/testReport/junit/Products.CMFQuickInstallerTool.tests.test_browser/QIBrowserTest/test_installProducts_post/): `Request must be POST`

**Comment by mauritsvanrees** [comment]
I fixed it by taking the working approach that I applied in [`pas.plugins.headers`](https://github.com/collective/pas.plugins.headers/commit/b057630d898d77641faf1f7d83b01008a567d882) last week. Should work on Plone 5.2 with old Zope and new Zope. And on 6.0 it should fix the last remaining failure.

@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
> And on 6.0 it should fix the last remaining failure.

It is still the plan to remove the whole package from 6.0, right?

**Comment by mauritsvanrees** [comment]
> It is still the plan to remove the whole package from 6.0, right?

Yes, that is still the plan.

**Comment by mauritsvanrees** [comment]
Ha, the Plone 6.0 PR job [succeeds](https://jenkins.plone.org/job/pull-request-6.0-3.7/) for the first time!
5.2 Py 2.7 has a failure that seems unrelated, but I have restarted it.

**Pull request merged**
